### ISSUE TITLE
Auto calculate PO bill due date

### ISSUE THREAD

**Issue by taylorcook-por** [Intacct/intacct-sdk-net#100]
I am sending over the PO information through the .NET SDK. The Due Date on the PurchasingTransactionCreate object is nullable, but when I try to pass nothing or leave it off altogether, I get the error "Nullable object must have a value". Wanting to leave it null so it can be calculated based off vendor terms

**Comment by taylorcook-por** [comment]
Any update on this?

**Comment by taylorcook-por** [comment]
Any update on this?

**Comment by intacctcoleenho** [comment]
This is going to be fixed in the next minor release.

**Comment by intacctcoleenho** [comment]
Now available in v2.3.0
