### ISSUE TITLE
Query dimensions

### ISSUE THREAD

**Issue by tqrecords** [Intacct/intacct-sdk-net#103]
Looks like you cannot query the DIMENSION object directly through the SDK:

`var readByQuery = new ReadByQuery { ObjectName = "Dimensions" };
client.Execute(readByQuery)`

The ReadByQuery puts together this code:

` <function controlid="{{$guid}}">
        <readByQuery>
          <object>DIMENSIONS</object>
          <fields>*</fields>
          <query/>
        </readByQuery>
      </function>`

Which is invalid. Is there another way to query this endpoint?

**Comment by jimmymcpeter** [comment]
It's a one off function, `getDimensions` -- https://developer.intacct.com/api/platform-services/dimensions/#list-dimensions
You'd need your own class that implements the IFunction interface...  Something like this:
```csharp
using Intacct.SDK.Xml;

namespace My.Intacct.Function
{
    public class DimensionsList : AbstractFunction
    {

        public DimensionsList(string controlId = "") : base(controlId)
        {
        }

        public override void WriteXml(ref IaXmlWriter xml)
        {
            xml.WriteStartElement("function");
            xml.WriteAttributeString("controlid", ControlId);

            xml.WriteStartElement("getDimensions");
            
            xml.WriteEndElement();

            xml.WriteEndElement();
        }
    }
}
```

**Comment by tqrecords** [comment]
Made the class as suggested with a custom Dimension object to convert the xml. Thank you.
