### ISSUE TITLE
ReadyByQuery Negate Comparison

### ISSUE THREAD

**Issue by jasontfrance** [Intacct/intacct-sdk-net#104]
It looks like using Negate in the ReadyByQuery Comparisons is putting a NOT in front of the Field Name.  I'm getting errors back from the Intacct Web Service.  But if I don't use Negate = true, then it's fine.  example searching a SODOCUMENT, EqualToString, SHIPVIA= 'USPS' works fine. But switching Negate to true, then the line kicks out as NOT SHIPVIA = 'USPS

![Capture1](https://user-images.githubusercontent.com/59661259/72000526-8119b580-3211-11ea-9d9c-69c31e890871.PNG)
' 
Error: DL02000001 Error There was an error processing the request.

**Comment by intacctcoleenho** [comment]
SHIPVIA is a relationship and not a field of SODOCUMENT.  You need to use SHIPVIA.NAME instead for SHIPVIA for this ReadByQuery.
