### ISSUE TITLE
AR Payment Create issue - Periods are closed

### ISSUE THREAD

**Issue by jtcolvin** [Intacct/intacct-sdk-net#105]
We get an error message that - "Periods are closed.  Your transaction date (xx/xx/xxxx) is within a period that's been closed.  You can add, modify, or delete a transaction only if the date of the transaction is within a period that's open." The customerPayment.DocumentDate is the date the payment of Credit Card is ran.  This works if the period is not closed. Any suggestions?

            var payment = new ArPaymentCreate()
            {
                CustomerId = billingCustomer.AccountingId,
                TransactionPaymentAmount = paymentAmount,
                PaymentMethod = "Credit Card",
                ReceivedDate = customerPayment.DocumentDate,
                ReferenceNumber = customerPayment.InvoiceId,
                AuthorizationCode = customerPayment.CreditCardAuthorizationCode,
                BankAccountId = bankAccountId,
                UndepositedFundsGlAccountNo = AppConfig.GetSetting("IntacctUndepositedFunds"),
                OverpaymentLocationId = AppConfig.GetSetting("IntacctOverpayment"),
            };

            var paymentItem = new ArPaymentItem()
            {
                ApplyToRecordId = Convert.ToInt32(soDocument.PRRECORDKEY),
                AmountToApply = paymentAmount,
            };

            payment.ApplyToTransactions.Add(paymentItem);

**Comment by jimmymcpeter** [comment]
You'll likely want to talk with whoever is closing the books and ask how they want the transaction booked into the subledger/general ledger.  It's not normal to reopen the books and reissue financial statements so you'll likely need to change the date.  You might try using the batchkey since those allow setting the GL posting date
