### ISSUE TITLE
Order Entry Transaction Update issue

### ISSUE THREAD

**Issue by mgfoster39047** [Intacct/intacct-sdk-net#107]
I'm trying to update an OE transaction and when I send the information I receive "Element 'update_sotransaction': The attribute 'key' is required but missing.. Line: 1, column: 0." I'm sending the Transaction definition and the Document number, but I am uncertain as to what the "key" that it is referring to is... any Ideas?

Here is the pertinent part of the code for reference:

OrderEntryTransactionUpdate update = new OrderEntryTransactionUpdate()
                {
                   //hard code invoice number
                    TransactionDefinition = "Contract Invoice",
                    DocumentNumber = "arbitrary invoice number"
                };
	        Task<OnlineResponse> updateTask = client.Execute(update);
                updateTask.Wait();
            
                Console.WriteLine("Updated Order Entry Transaction Contract Invoice ");

**Comment by jimmymcpeter** [comment]
`TransactionId` -- https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK.Tests/Functions/OrderEntry/OrderEntryTransactionUpdateTest.cs#L42
