### ISSUE TITLE
InventoryControl-TransactionItemDetail-WriteXml Issue

### ISSUE THREAD

**Issue by anish-alias** [Intacct/intacct-sdk-net#108]
InventoryControl-TransactionItemDetail-WriteXml has a wrong logic. There are ITEMS that are both LOT and SERIAL controlled. In such scenario both values to be passed. instead of elseif it should be if.

            if (!string.IsNullOrWhiteSpace(SerialNumber))
            {
                xml.WriteElement("serialno", SerialNumber);
            }
            elseif (!string.IsNullOrWhiteSpace(LotNumber))
            {
                xml.WriteElement("lotno", LotNumber);
            }

**Comment by intacctcoleenho** [comment]
This is working as designed.  
Per the documentation for the XML API, serialno and lotno are mutually exclusive: https://developer.intacct.com/api/order-entry/order-entry-transactions/#create-order-entry-transaction-legacy
Per the DTD, itemdetail is defined as: <!ELEMENT itemdetail (componentid?, quantity?, (serialno | lotno)?, aisle?, row?, bin?, itemexpiration?)> 
Reference DTD here: https://github.com/Intacct/intacct_dtd/blob/master/v2.1/intacct_request_objects.v2.1.dtd

**Comment by anish-alias** [comment]
Hi, But when an ITEM is both LOT and SERIAL controlled in Intacct system is throwing exception when only SERIAL number is passed. I tried the XML API via POSTMAN with both LOT and SERIAL number provided and it worked.

![image](https://user-images.githubusercontent.com/33719383/94103280-d6eec600-fe51-11ea-9cda-095a89c76865.png)

**Comment by intacctcoleenho** [comment]
Fix targeted for next release
