### ISSUE TITLE
Global Consolidation not working due to incorrect XML serialization of TRUE/FALSE

### ISSUE THREAD

**Issue by chrisperish** [Intacct/intacct-sdk-net#109]
When I try to post a Consolidation Intacct returns an error saying "Error: Bl01001974 You must specify a value(T OR F) for offline field."  

I ran Fiddler and intercepted the traffic. The xml that is posted from the SDK is `<offline>true</offline>.`  If I make the exact same post via Postman it fails.  If I modify the payload to `<offline>T</offline>` it works.  

I believe the code needs to be changed to serialize true and false as T and F for the XML payloads.

**Comment by intacctcoleenho** [comment]
This will be fixed in the next minor release

**Comment by intacctcoleenho** [comment]
Now available in v2.3.0
