### ISSUE TITLE
Issues with ChargeCardTransactionCreate

### ISSUE THREAD

**Issue by resihunter** [Intacct/intacct-sdk-net#110]
Can someone provide an example on how to use ChargeCardTransactionCreate? I'm having issues with a required field called ccpayitem. Error message:

Element 'ccpayitems': Missing child element(s). Expected is ( ccpayitem )

ChargeCardTransactionCreate doesn't have a property called ccpayitems. My guess is that I need to use ChargeCardTransactionCreate.Lines, but I don't know how to implement that either. 

            ChargeCardTransactionCreate ccCreate = new ChargeCardTransactionCreate()
            {
                ChargeCardId = "CapOneCorpNew",
                TransactionDate = DateTime.Now,
               // Lines = ?,
            };

**Comment by jimmymcpeter** [comment]
The tests here should help you -- 
https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK.Tests/Functions/CashManagement/ChargeCardTransactionCreateTest.cs#L106

https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK.Tests/Functions/CashManagement/ChargeCardTransactionLineCreateTest.cs#L74
