### ISSUE TITLE
Inventory Control Create Item missing required field UOMGroup as a property

### ISSUE THREAD

**Issue by LouDavis951** [Intacct/intacct-sdk-net#124]
Working with the Intacct SDK in VS 2017 and came across an issue with creating new items  within Inventory control.  The required field UOM Group is not a property that can be set like UOM can be.   This and any other required fields should be properties within ItemCreate.

**Comment by intacctcoleenho** [comment]
Do you mean field "UOMGPR" in the ItemCreate.cs file?

**Comment by LouDavis951** [comment]
Correct.  I used NUGET to pull down the SDK.  UOMGrp was not exposed with other the item properties, so I could not set it, which resulted in the error about it being required.   I worked around the issue by not using the SDK at all and simply making a Web API call to Intacct directly using an httpclient call.

**Comment by intacctcoleenho** [comment]
Could you provide an example of the request you were trying to use for ItemCreate with the SDK?

**Comment by LouDavis951** [comment]
Here is the code I had previously.  
Intacct.SDK.Functions.InventoryControl.ItemCreate itemCreate = new Intacct.SDK.Functions.InventoryControl.ItemCreate();
                    itemCreate.ItemId = dataRow["ITEMID"].ToString();
                    itemCreate.ItemName = dataRow["NAME"].ToString();
                    itemCreate.ItemType = dataRow["ITEMTYPE"].ToString(); 
                    itemCreate.ProductLineId = dataRow["PRODUCTLINEID"].ToString(); 
                    itemCreate.CostMethod = dataRow["COST_METHOD"].ToString();
                    itemCreate.Active = true;
                    itemCreate.UnitOfMeasure = dataRow["BASEUOM"].ToString(); 
                    itemCreate.CustomFields = new Dictionary<string, dynamic>();
                    itemCreate.CustomFields.Add("E2B_PRODUCT_CATEGORY_NAME", dataRow["E2B_PRODUCT_CATEGORY_NAME"].ToString());
                    itemCreate.CustomFields.Add("E2B_PRODUCT_CATEGORY_TYPE", dataRow["E2B_PRODUCT_CATEGORY_TYPE"].ToString());
                    itemCreate.CustomFields.Add("E2B_STRAIN_NAME", dataRow["E2B_STRAIN_NAME"].ToString());
                    itemCreate.CustomFields.Add("E2B_UNIT_CBD_PERCENT", dataRow["E2B_UNIT_CBD_PERCENT"]);
                    itemCreate.CustomFields.Add("E2B_UNIT_CBD_CONTENT", dataRow["E2B_UNIT_CBD_CONTENT"]);
                    itemCreate.CustomFields.Add("E2B_UNIT_THC_PERCENT", dataRow["E2B_UNIT_THC_PERCENT"]);
                    itemCreate.CustomFields.Add("E2B_UNIT_THC_CONTENT", dataRow["E2B_UNIT_THC_CONTENT"]);

                    IntacctUtilities.TaskResult taskResult = _IntacctUtilities.TaskQuery(itemCreate, false, false);

Stepping through it as it ran, I did verify a BaseUOM existed.  The error message stated that I needed a UOMGrp or had to set one as default.  We tried setting one up a default in Intacct, but that didn't seem to make a difference.

**Comment by intacctcoleenho** [comment]
Thanks for the code, however, I think we'll need to take this offline and triage it with you and the team.  Could you provide us with a ticket here https://www.sageintacct.com/support so we can track this and work together with you on finding a resolution?  Please ask this support request to be directly escalated to product / engineering.
