### ISSUE TITLE
Batch Operation to create Customer

### ISSUE THREAD

**Issue by letoncse** [Intacct/intacct-sdk-net#131]
Hi All,How i can run batch operation? I would like to create multiple customer. I'm using .net SDK. Please see my example for single customer.  

```
CustomerCreate create = new CustomerCreate()
        {
            CustomerName = "Test User",
            CustomFields= new Dictionary<string, dynamic>() { { "AccountRef", "Peter" } },
        };
        Task<OnlineResponse> createTask = client.Execute(create);
        createTask.Wait();
```
How I achieved to send multiple customer request means batch operation for customer?
@intacctcoleenho @jimmymcpeter Could you give me a sample code please.
Thanks, Liton

**Comment by jimmymcpeter** [comment]
Check out the block of code in the unit test here -- https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK.Tests/OnlineClientTest.cs#L229-L242

**Comment by letoncse** [comment]
Thank you @jimmymcpeter
