### ISSUE TITLE
ContactCreate missing IsoCountryCode

### ISSUE THREAD

**Issue by jasontfrance** [Intacct/intacct-sdk-net#133]
I don't see where I can add the ISO Country Code to the Contact during a Create or Update.  The AbstractContact class appears to only have Country.  If the ISO Country Codes are checked on the Company General page, then both values are required (name & code), correct?

**Comment by letoncse** [comment]
Hi @jasontfrance ,
you can add countrycode in your request. like below. 
```
CustomerCreate create = new CustomerCreate()
 {  
  IsoCountryCode="UK"
}
```
Thanks !

**Comment by jasontfrance** [comment]
Not Customer.  Contact

**Comment by letoncse** [comment]
have you pass below all fields value ? 

                ```
                xml.WriteElement("ADDRESS1", AddressLine1);
                xml.WriteElement("ADDRESS2", AddressLine2);
                xml.WriteElement("CITY", City);
                xml.WriteElement("STATE", StateProvince);
                xml.WriteElement("ZIP", ZipPostalCode);
                xml.WriteElement("COUNTRY", Country);

```

**Comment by letoncse** [comment]
Please see below my sample code that is working fine.
```

ContactCreate contactCreate = new ContactCreate()
            {
                ContactName="Test Contact",
                PrintAs= "Test Contact",
                AddressLine1 = "Dublin",
                AddressLine2 = "Dublin 2",
                City = "Dublin",
                StateProvince = "Dublin",
                ZipPostalCode = "F345h",
                Country = "Ireland",
            };
            Task<OnlineResponse> contactCreatetask = client.Execute(contactCreate);
            contactCreatetask.Wait();
```

**Comment by jasontfrance** [comment]
Yes, my client is using the ISO Country Code required field on the Company General page.  And I need to pass in the IsoCountryCode along with the Country when creating a Contact.  But in the .NET ContactCreate there isn't an IsoCountryCode.  Only a Country.  I need both since in the Company General page the ISO Country Code required is set

**Comment by jasontfrance** [comment]
https://developer.intacct.com/api/company-console/contacts/
 When ISO country codes are enabled in a company, both COUNTRY and ISOCOUNTRYCODE must be provided

**Comment by dylan-holt-sage** [comment]
Code for this has been merged and will be coming with a future release which is TBD. Closing this issue.
