### ISSUE TITLE
Support for .NET 5.0

### ISSUE THREAD

**Issue by AmitaKhatri** [intacct/intacct-sdk-net#138]
Would this library be supported in .NET 5.0 framework?

**Comment by mottykohn** [comment]
I've been using it against .NET 5.0 with no issues. (As a Windows Service)

**Comment by Paul-Schroeder** [comment]
Hi @AmitaKhatri, as a .NET Standard 2.0 library it should "just work". However, I did submit a pull request that specifically implements multi-targeting for .NET 5 here:  [https://github.com/Intacct/intacct-sdk-net/pull/155](url)

Or, you could just take it from my branch here: [https://github.com/Paul-Schroeder/intacct-sdk-net/tree/feature/net5](url)

**Comment by dylan-holt-sage** [comment]
Hey @Paul-Schroeder/ @AmitaKhatri / @mottykohn , we are planning to jump to .NET 6 for next release and stick with LTS versions of .NET going forward.
