### ISSUE TITLE
Way to set Intacct API URL by the Consumer to Mock the Response in Real Integration

### ISSUE THREAD

**Issue by Reena-Patel** [Intacct/intacct-sdk-net#145]
Would it be possible to set other than the Intacct API URL which does not intacct.com or an Intacct API URL?  We want to provide our own URL to send the own response so that real integration can be tested. suppose 503 error then we have our own logic to handle 503 so we want to test that logic in a real environment which requires to use own API URL to send 503 response.

Stripe .net SDK is providing a way to set stripe API URL: https://github.com/stripe/stripe-dotnet/blob/3b2ed3af048889e19ecdaaf2edcdea275848f317/src/Stripe.net/Services/_common/RequestOptions.cs

Twilio .ent SDK is providing a way too:  https://www.twilio.com/docs/libraries/csharp-dotnet/custom-http-clients-dot-net-framework?code-sample=code-how-to-pass-a-twiliorestclient-2&code-language=C%23&code-sdk-version=default

**Comment by jimmymcpeter** [comment]
Check out the mockhandler in the unit test here -- https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK.Tests/SessionProviderTest.cs#L71

**Comment by jimmymcpeter** [comment]
Here is an example with a 502 -- https://github.com/Intacct/intacct-sdk-net/blob/d1d20ac6a0dbd52ad345f711a96e66d41e0dad83/Intacct.SDK.Tests/Xml/RequestHandlerTest.cs#L217

**Comment by intacctcoleenho** [comment]
Please reopen this request if your question has not been answered.
