### ISSUE TITLE
Global Consolidation not working due to incorrect XML serialization of TRUE/FALSE 

### ISSUE THREAD

**Issue by chrisperish** [Intacct/intacct-sdk-net#148]
Similar to issue 109

When I try to post a Consolidation Intacct returns an error saying "Error: Bl01001974 You must specify a value(T OR F) for updatesucceedingperiods field."

I ran Fiddler and intercepted the traffic. The xml that is posted from the SDK is <updatesucceedingperiods>true</updatesucceedingperiods>. If I make the exact same post via Postman it fails. If I modify the payload to <updatesucceedingperiods>T</updatesucceedingperiods> it works.

I believe the code needs to be changed to serialize true and false as T and F for the XML payloads.

**Comment by dylan-holt-sage** [comment]
Hey @chrisperish, can you share the request you have been using for this? Just want to check on a few things regarding this matter :)

**Comment by dylan-holt-sage** [comment]
Hey @chrisperish, I have resolved the issue you were facing and the changes will be coming in a future release which is TBD. Thanks and I'll be closing this issue.
