### ISSUE TITLE
Contacts with COMMA Return non-existing

### ISSUE THREAD

**Issue by bilderbach** [Intacct/intacct-sdk-net#149]
When updating contacts with a comma(,) in the name such as "lastname,firstname" format the new API will return an error saying the contact could not be found even though the contact does indeed exist.
(I think you will find the same issue with "readByName" call).

Tried to work around the issue by looking them Contact up and then using RecordNumber, but the RecordNumber parameter is not available in the SDK, so would really like to see that.

Thanks for your help in getting this working!
-R

HOW TO REPRODUCE ISSUE:
Load postman with UpdateContact template.

Replace:
`
	<RECORDNO>11</RECORDNO>
	<PRINTAS>hello world</PRINTAS>
`

With:
`
	<CONTACTNAME>USE_A_CONTACT_NAME_WITH_LAST,FIRST</CONTACTNAME>
	<EMAIL1>NEW@EMAIL.COM</EMAIL1>
`

ERROR RETURNED:
`
	<error>
		<errorno>Cannot update non-existing CONTACT with CONTACTNAME=USE_A_CONTACT_NAME_WITH_LAST,FIRST. 
               </errorno>
		<description></description>
		<description2> [Support ID: FHbQVEB033%7EYCQ5fP0z2Sh-SnKW-jnbHQAAAAU]</description2>
		<correction></correction>
	</error>
`

**Comment by karstenintacct** [comment]
This is an issue that has been addressed in the past. In order to retrieve contacts by name that include comma, please escape the comma:

<readByName>
          <object>CONTACT</object>
          <keys>Alvarado\, Mary D.</keys>
          <fields>*</fields>
        </readByName>

This will interpret the comma correctly.

Thank you 
Karsten
