### ISSUE TITLE
Recurring order entry transactions - Missing from SDK?

### ISSUE THREAD

**Issue by WiNiFiX** [Intacct/intacct-sdk-net#153]
Hi there, I have hunted through the SDK but am unable to find your logic for recurring order entry transactions as per:
https://developer.intacct.com/api/order-entry/recurring-order-entry-transactions/

**Comment by dylan-holt-sage** [comment]
I have created the objects for Recurring Order Entry Transactions and the changes will be coming in a future release which is TBD. Thanks and I'll be closing this issue.

**Comment by WiNiFiX** [comment]
Kind of a few months late :), but no worries, we added the support ourselves.
