### ISSUE TITLE
ContactName is not getting updated in Intacct on updating user email in CustomerUpdated object

### ISSUE THREAD

**Issue by patelveep** [intacct/intacct-sdk-net#154]
Currently, on updating the user email the neither the Primary UserEmail or ContactName is getting updated in the Intacct customer account. We are getting **BL03000019**  error no with the error message - The contact testaccount@gmail.com does not exist.

It is expected that ContactName should be passed in the DisplayContact object in the SDK. But currently, it is not having the parameter.  If you can please look into this

**Comment by Reena-Patel** [comment]
Currently not able to provide CONTACT_LIST_INFO in the [CustomerCreate](https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/AccountsReceivable/CustomerCreate.cs)/ [CustomerUpdate](https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/AccountsReceivable/CustomerUpdate.cs) request. 

If you can please look into this also.

**Comment by karstenintacct** [comment]
Hi,
could you please share a code consumption sample, that doesn't work for you.
If this is not supported through the API, then it is not something we can overcome in the SDK, but before making any early conclusions, I am recommending to get more details.

Thank you
Karsten

**Comment by dylan-holt-sage** [comment]
Closing as stale, if still an issue or want it resolved, please re-open and assign to me.
