### ISSUE TITLE
Newly created customers not being mapping to the Top-Level

### ISSUE THREAD

**Issue by vehs-dwhitney** [Intacct/intacct-sdk-net#157]
Hi,

Currently, my team is trying to map all newly created/exported customers to the Top-Level of Intacct instead of the local/custom entities (but are having issues). When talking with the Intacct support team, we were told to request/send a SessionId along with our request (with an empty location) in order to map customers to the Top Level. However, even after setting this SessionId, customers are still being mapped to our local entity.

My questions is, is there any other way to explicitly map customers to this TopLevel? Is it possible we need to do something else in addition to setting this SessionId? (e.g. an account setting, Config values, etc). For reference, the SessionId that was set was via the SessionId property from the ClientConfig class of the Intacct .NET SDK. (2.3.0).

**Comment by karstenintacct** [comment]
The authentication request should create a top-level session if no location ID is passed in unless the user you are working with has no permissions to the top level. Then the login to an entity will be triggered. 

When performing the authentication, please set a breakpoint to see if the locationId is really empty, when generated.

Please file a case with support in case this is not working and get it routed to me. We don't really face issues of this kind with the SDK, so it looks like a one-off to look closer at.

I am going to close this issue and hopefully, you will be able to resolve it or open a support case, addressed to me.

Thank you 
Karsten Manske

**Comment by karstenintacct** [comment]
And if logged into an entity, there is no way of mapping it to the top-level, just to answer your question.

Karsten
