### ISSUE TITLE
BL01001973 Tax details are either missing or don't belong to the tax solution

### ISSUE THREAD

**Issue by letoncse** [Intacct/intacct-sdk-net#160]
I'm getting error while creating invoice "BL01001973 Tax details are either missing or don't belong to the tax solution . Ensure each line item has a tax detail that belongs to the applicable tax solution." . Please see my below sample code. How to send  “taxsolutionid”  and “detailid” value ? 

```
InvoiceCreate inCreate1 = new InvoiceCreate()
            {
                CustomerId = "C-002749",
                RecordNo= 13390,
                DueDate = DateTime.Now.AddDays(5),
                InvoiceNumber = "14527",
                TransactionDate = DateTime.Now,
                BaseCurrency = "EUR",
                TransactionCurrency = "EUR",
                Description = "Description",                
                GlPostingDate = DateTime.Now,

            };
            InvoiceLineCreate invoiceLineCreate1 = new InvoiceLineCreate();

            invoiceLineCreate1.CustomerId = "C-002749";
            invoiceLineCreate1.GlAccountNumber = "400010";
            invoiceLineCreate1.TransactionAmount = 20;
            
            invoiceLineCreate1.TotalDue = 20;
            invoiceLineCreate1.TotalPaid = 0;
            invoiceLineCreate1.LocationId = "1000";
            invoiceLineCreate1.Memo = "Services Rendered";
            invoiceLineCreate1.DepartmentId = "D50";

            inCreate1.Lines.Add(invoiceLineCreate1);
            Task<OnlineResponse> readTaskin = client.Execute(inCreate1);
            readTaskin.Wait();
```
Please see this screenshot. Thanks !
![image](https://user-images.githubusercontent.com/1812631/114731779-eb38d880-9d39-11eb-9cd1-7c6e3bab43ff.png)

**Comment by karstenintacct** [comment]
Hi there,
I have talked to Charlie this morning about the issue you have raised.
I will be discussing this enhancement with our team and will then have a better idea of how soon this can be done. For SDKs, we don't follow any SLAs, as this would be the case for an actual issue in the API.
In order for you to proceed faster, you can also modify the SDK and even create a pull request.
Thank you
Karsten

**Comment by brightjijinr** [comment]
I am starting this.

**Comment by dylan-holt-sage** [comment]
Code has been reviewed and merged after sanity check. Change will be coming in a future release which is TBD. Thanks and I'll be closing this issue.
