### ISSUE TITLE
Get APPayments Bugs

### ISSUE THREAD

**Issue by babichVA** [Intacct/intacct-sdk-net#161]
Hi. I can't get all fields of APPayment. Please, help me.

APPYMT is name of APPayment object ( https://developer.intacct.com/api/accounts-payable/ap-payments/#get-ap-payment )

            string entityName = "APPYMT";
            string[] fields = { "PAYMENTDATE", "DOCNUMBER", "RECORDNO", "TRX_PAYMENTAMOUNT",
                "FINANCIALENTITY", "APPYMTDETAILS", "PAYMENTMETHOD"};
            ClientConfig clientConfig = new ClientConfig()
            {
                CompanyId = "*********",
                UserId = "*******",
                SenderPassword = "*******",
                SenderId = "*******",
                UserPassword = "*********"
            };

            OnlineClient client = new OnlineClient(clientConfig);

            List<Result> results = new List<Result>();
            const int pageSize = 100;

            SelectBuilder selectBuilder = new SelectBuilder();
            ISelect[] fields = selectBuilder.
            Fields(fieldsName).GetFields();

            QueryFunction query = new QueryFunction()
            {
                SelectFields = fields,
                FromObject = objectName,
                CaseInsensitive = true,
                PageSize = pageSize
            }; 

            Task<OnlineResponse> task = client.Execute(query);
            task.Wait();
            OnlineResponse response = task.Result;

Inner Exception on line task.Wait 

ResultException: Result status: failure for Control ID: f7c8a2ff-ec54-4e7c-acc2-9107e882532b - XL03000006 The following fields cannot be queried: [ appymt: [PAYMENTDATE, TRX_PAYMENTAMOUNT, FINANCIALENTITY, APPYMTDETAILS] ] [Support ID: tcvBwEB032%7EYHitsP0W26x-Nz8WzC1A9gAAAAg]

Only this 3 fields { "DOCNUMBER", "RECORDNO", "PAYMENTMETHOD"}; are available.

Thank you.

**Comment by karstenintacct** [comment]
This is not an SDK issue but should be supported through the API.

I will follow up with AP team to find out how to retrieve these fields / information correctly

Karsten

**Comment by karstenintacct** [comment]
I am going to close this issue, since it is not related to the SDK. Please open a customer support case, to get the API problem addressed.
