### ISSUE TITLE
What is the current (non-legacy) way to create invoices/sales orders (that are invoices)?

### ISSUE THREAD

**Issue by gawmanarnar** [Intacct/intacct-sdk-net#162]
I'm finding that both Create Invoice and Create Sales Order are listed as Legacy in the API reference. What is the correct way to do this for new software?

**Comment by fdtaljaard** [comment]
> I'm finding that both Create Invoice and Create Sales Order are listed as Legacy in the API reference. What is the correct way to do this for new software?

I have the same question.

**Comment by karstenintacct** [comment]
Hi there,
this has a little bit of history. Sage Intacct has a 2.1 API, which is for example create_sotransaction or create_invoice.
After introducing 3.0 API, all 2.1 API were listed as legacy. However, the 3.0 implementation is not supported for these APIs. Therefore the latest supported API function, which is 2.1 in this case will remain supported in the SDK.

I am going to close this issue, as there is no change required for for SDK at this point.

Thank you 
Karsten
