### ISSUE TITLE
Inventory Control/Warehouse Transfers

### ISSUE THREAD

**Issue by fdtaljaard** [Intacct/intacct-sdk-net#165]
Object ICTRANSFER is not supported in the SDK.

**Comment by fdtaljaard** [comment]
> Object ICTRANSFER is not supported in the SDK.
This is my custom object implementation that will work for my requirements. 
`   public class WarehouseTransferCreateLine
    {
        public string In_Out { get; set; }
        public string ItemId { get; set; }
        public string WarehouseId { get; set; }
        public string Quantity { get; set; }
        public string Unit { get; set; }
        public string LocationId { get; set; }

        public void WriteXml(ref IaXmlWriter xml)
        {
            xml.WriteStartElement("ICTRANSFERITEM");
            xml.WriteElement("IN_OUT", this.In_Out, true);
            xml.WriteElement("ITEMID", this.ItemId);
            xml.WriteElement("WAREHOUSEID", this.WarehouseId);
            xml.WriteElement("QUANTITY", this.Quantity, true);
            xml.WriteElement("UNIT", this.Unit);
            xml.WriteElement("LOCATIONID", this.LocationId);
            xml.WriteEndElement(); //ICTRANSFERITEM
        }
    }
    public class WarehouseTransferCreate : AbstractFunction
    {
        public string Description { get; set; }

        public WarehouseTransferCreate(string controlId = null) : base(controlId)
        {
            this.Lines = new List<WarehouseTransferCreateLine>();
        }

        public List<WarehouseTransferCreateLine> Lines { get; set; }
        
        public override void WriteXml(ref IaXmlWriter xml)
        {
            xml.WriteStartElement("function");
            xml.WriteAttribute("controlid", this.ControlId, true);
            xml.WriteStartElement("create");
            xml.WriteStartElement("ICTRANSFER");

            xml.WriteElement("TRANSACTIONDATE", DateTime.Now.ToString());
            xml.WriteElement("DESCRIPTION", this.Description);

            xml.WriteStartElement("ICTRANSFERITEMS");
            if (this.Lines.Count > 0)
            {
                foreach (WarehouseTransferCreateLine line in this.Lines)
                    line.WriteXml(ref xml);
            }
            xml.WriteEndElement(); // ICTRANSFERITEMS
            xml.WriteEndElement(); // create
            xml.WriteEndElement(); // ICTRANSFER
            xml.WriteEndElement(); // function
        }
    }

    public class WarehouseTransfer : Base
    {
        public string Post(IList<Contract.Transaction> transactions, bool post)
        {
            try
            {
                WarehouseTransferCreate function = new WarehouseTransferCreate {
                    Description = "Granite"
                };

                foreach (var trans in transactions)
                {
                    // OUT = FromLocation
                    var line = new WarehouseTransferCreateLine
                    {
                        In_Out = "O",
                        LocationId = "700",
                        WarehouseId = trans.FromLocation,
                        ItemId = trans.Code,
                        Quantity = trans.ActionQty.ToString(),
                        Unit = trans.UOM
                    };
                    function.Lines.Add(line);

                    // IN = ToLocation
                    line = new WarehouseTransferCreateLine
                    {
                        In_Out = "I",
                        LocationId = "700",
                        WarehouseId = trans.ToLocation,
                        ItemId = trans.Code,
                        Quantity = trans.ActionQty.ToString(),
                        Unit = trans.UOM
                    };
                    function.Lines.Add(line);
                }

                Task<OnlineResponse> createTask = base._client.Execute(function);
                createTask.Wait();
                OnlineResponse createResponse = createTask.Result;
                Result createResult = createResponse.Results[0];

                int recordNo = Convert.ToInt32(GetResult(createResult.Data[0], "RECORDNO"));

                Read read = new Read()
                {
                    ObjectName = "ICTRANSFER",
                    Fields = { "DOCNO" },
                    Keys = { recordNo }
                };

                Task<OnlineResponse> task = base._client.Execute(read);
                task.Wait();

                OnlineResponse response = task.Result;
                Result result = response.Results[0];

                var docNo = GetResult(result.Data[0], "DOCNO");

                return docNo;
            }
            catch (Exception ex)
            {
                throw new Exception(HandleException(ex));
            }
        }

        private string GetResult(System.Xml.Linq.XElement item, string key)
        {
            return item.Element(key).Value;
        }
    }`

**Comment by dylan-holt-sage** [comment]
I have created the objects for Warehouse Transfers and the changes will be coming in a future release which is TBD. Thanks and I'll be closing this issue.
