### ISSUE TITLE
Session Time Out

### ISSUE THREAD

**Issue by lbTustin** [intacct/intacct-sdk-net#166]
Is there a way to get the session time out for the session id retrieved through ApiSessionCreate() That does not seem to be accessible in the response

**Comment by lbTustin** [comment]
Hoping to get this answered and have a related question.  It seems the response is a protected property.  I'm would like to see the response in its native XML format before the client parses it.  Is that possible?

**Comment by dylan-holt-sage** [comment]
Hey @lbTustin, sorry for the late response....... For the session time out, that value **should** be calculated from the **sessionTimeStamp** where:
sessionTimeOut = sessionTimeStamp + session duration (specified by user/company configurations).

I have noticed that there is a "ToDo" item for a few fields not yet added in **Authentication.cs** and **sessionTimeStamp** is one of those fields. So I will be adding that in preparation for our next .NET release, date is TBD 2022.

Apologies for the delay on this matter.

**Comment by dylan-holt-sage** [comment]
Changes for this will be going into the next release. Closing this issue
