### ISSUE TITLE
IaXmlWriter unable to handle custom fields of DateTime

### ISSUE THREAD

**Issue by patrick-acst** [intacct/intacct-sdk-net#178]
This is an issue we ran into and resolved and wanted to pass this on.  Found that when we had a custom DataTime field that the xml writer would throw an exception when WriteCustomFieldsImplicit tried to pass the DateTime as a string parameter to the WriteElement function.  Through some investigation, realized the WriteElement overload that accepts DateTime is not accessible unless explicitly called.  Added a third overload to IaXmlWriter that seems to work and causes no other code conflicts.

public void WriteElement(string localName, DateTime? value, bool writeNull, string format = IntacctDateTimeFormat)
{
	if (!value.HasValue)
	{
		if (writeNull == true)
		{
			_writer.WriteElementString(localName, "");
		}
	}
	else
	{
		_writer.WriteElementString(localName, value == default(DateTime) ? "" : value.Value.ToString(format));
	}
}

**Comment by dylan-holt-sage** [comment]
Hey @patrick-acst, I looked in the IaXmlWriter.cs and noticed that we already have a WriteElement function that is nearly identical to what you've provided above (line 266 in the class currently in the repository).

Correct me if I'm wrong, but the only difference that I see is that our boolean parameter is an optional parameter which defaults to false if not passed in.

**Comment by alabounty** [comment]
I'm experiencing this same issue with a DateTime custom field. I created a simple test to demonstrate the issue that can be found here: https://github.com/alabounty/IntacctSDKCustomDateTimeExample/

**Comment by dylan-holt-sage** [comment]
This issue will be fixed in 3.2.0 branch, added logic for DateTime custom fields to leverage the existing code flow that was left out for custom fields. Release TBD
