### ISSUE TITLE
CustomField strings are converted to integers

### ISSUE THREAD

**Issue by JayConverse** [Intacct/intacct-sdk-net#179]
I opened a support case with Sage, but thought it would be good here, too.  I'm using C# with a form on which the user enters the custom field ID.  SageString and SageNum are functions I used to read Sage300 query values.

...
journalEntryLineCreate.ProjectId = SageString(cs0120GLEntries, "PROJECT");
journalEntryLineCreate.TransactionAmount = Math.Round(SageNum(cs0120GLEntries, "OPENBAL"), 2);
journalEntryLineCreate.VendorId = SageString(cs0120GLEntries, "VENDOR");
journalEntryLineCreate.LocationId = this.lblLocation.Text;
if (this.txtUserDefined.Text.Trim() != "")
{
       journalEntryLineCreate.CustomFields.Add("GLDIM" + this.txtUserDefined.Text, SageString(cs0120GLEntries, "USERDEFINED"));
}
journalEntryCreate.Lines.Add(journalEntryLineCreate);
...

The problem is that the USERDEFINED values are like 001, 002, 010, 011, etc.  Then I get an error like this:

Result status: failure for Control ID: 055f5cbf-ab27-4208-98cc-d1cb965ae049 - Cannot relate new GL Entry to non-existing MBP object with id = 2 (by relationship RGLDIM101000000018116_10060) [Support ID: V%40J0AEB031%7EYXBHXP0%402L--FUKWPun%40jgAAABU] - BL01001973 Could not create glentry record! - BL01001973 Could not create glbatch record! - BL01001973 Could not create GLBatch record!"

The error above is for "id = 2". But the value I passed was 002.  If I pass 009, the error is for "id = 9".  When I pass values like "A15", then it simply crashes with:

Result status: failure for Control ID: c80d1582-9b78-4fe2-81c6-dd284a11466b - DL02000001 Error There was an error processing the request. - BL01001973 Could not create glentry record! - BL01001973 Could not create glbatch record! - BL01001973 Could not create GLBatch record!

Maybe it's because WriteElement inside WriteCustomFieldsImplicit is overloaded?

**Comment by dylan-holt-sage** [comment]
@JayConverse, what is the request XML that is generated for this case?

**Comment by JayConverse** [comment]
I forgot I posted here. Thanks for getting back, I figured out the problem.  For custom dimensions, you can't pass in the actual text values like you can with Customers, Classes, and Departments, you have to pass in the internal ID, in other words, "002" maps to 1000, "013" maps to 1001, etc.

**Comment by dylan-holt-sage** [comment]
Awesome :) glad you were able to get around the issue.
