### ISSUE TITLE
Warehouse transfers when lot tracking is on

### ISSUE THREAD

**Issue by sightsciences** [intacct/intacct-sdk-net#186]
Hello - is it possible to do warehouse transfers via the SDK as currently setup? I have tried a few things and am not getting anywhere.

Trying to do a simple transfer of item X from warehouse Y to warehouse Z but we use lot tracking so I am getting Tracking information not provided for '1-102' in Line# 1. Please provide the tracking details and try again [Support ID: 5fXIo%7EYZLlpWE1BLA3Mlb0QgFy-gAAAAA]

I added lotno (which seems to be the field name on the item detail level for inventory transactions), etc. but no dice...any help would be appreciated!

**Comment by sightsciences** [comment]
Nevermind figured it out by digging around Postman. Not sure why TRACKINGENTRY is not documented anywhere...

 public class TRACKINGENTRY
            {              
                public string DOCENTRYNO { get; set; }              
                public string ITEMID { get; set; }              
                public string QUANTITY { get; set; }               
                public string TRACK_QUANTITY { get; set; }               
                public string SERIALNO { get; set; }              
                public string LOTNO { get; set; }              
                public string AISLEKEY { get; set; }
                public string ROWKEY { get; set; }
                public string BINKEY { get; set; }
                public string EXPIRATION { get; set; }
                public string SALE_PUR_TRANS { get; set; }
                public string AISLEID { get; set; }
                public string BINID { get; set; }
                public string ROWID { get; set; }
                public string WHENCREATED { get; set; }
                public string WHENMODIFIED { get; set; }
                public string CREATEDBY { get; set; }
                public string MODIFIEDBY { get; set; }
            }

**Comment by dylan-holt-sage** [comment]
@sightsciences, can you please share how you found that?

**Comment by sightsciences** [comment]
It's been a little while so I am fuzzy but I was messing with the postman scripts Intacct has and noticed the TRACKINGENTRY object when a result set got returned, and eventually I found it somewhere buried in their documentation (as just a mentioned object, no direct documentation on it)

From there I just pieced together what I figured was the requirements and eventually got the API to a happy point - so our integration is working fine.

Really not sure how it is not a distinct callout in the documentation (or at least was not back when I ran in to this) but I can only assume it isn't used often? But I feel like lot tracking is a pretty common thing...

***@***.***
Jason Barner
Technical Application Analyst
4040 Campbell Ave, Suite 100
Menlo Park, CA 94025
Cell 954.256.3637
