### ISSUE TITLE
Support for update statements from Q4 2021 release?

### ISSUE THREAD

**Issue by ZacP** [intacct/intacct-sdk-net#188]
Hi,

With the release of the Q4 2021 release, there has been API support for updates, such as https://developer.intacct.com/api/accounts-receivable/ar-advances/#update-ar-advance
Is there a planned update for this with the SDK?  If not, is there a way to make a direct XML update call via the SDK currently?

Thanks

**Comment by ZacP** [comment]
Hi,

Could we please get a response on this?

Thanks

**Comment by dylan-holt-sage** [comment]
@ZacP, I'll work on this as part of an upcoming release, date is TBD. Sorry for the delay.

**Comment by dylan-holt-sage** [comment]
@ZacP, Changes have been completed and will be in next release, date TBD
