### ISSUE TITLE
Facing issue , Result status: failure for Control ID:"" Multivisibility is not subscribed. Cannot set up multivisibility. 

### ISSUE THREAD

**Issue by ThinkrAstha** [intacct/intacct-sdk-net#189]
I am creating a new vendor in Intacct using Intacct SDK
This is how I am passing the object via VendorCreate API call
VendorCreate createVendor = new VendorCreate()
                                {

                                    VendorName = vendor.Name,
                                    PrimaryEmailAddress = vendor.Email,
                                    CompanyName = vendor.CompanyName,
                                    AddressLine1 = vendor.Address1,
                                    AddressLine2 = vendor.Address2,
                                    City = vendor.City,
                                    StateProvince = vendor.State,
                                    DefaultCurrency = vendor.Currency,
                                    ZipPostalCode = vendor.Zip,
                                    Country = vendor.Country,
                                    Active = vendor.Status,
                                    AchBankAccountNo = vendor.AP_Account.ToString(),
                                    RestrictedLocations = RestrictedLocations,
                                    RestrictedDepartments = RestrictedDepartments
                                };

Initially, when I posted the object without Restricted Location, Restricted Departments, everything seemed to be working fine. 
After I added Restricted Locations,Restricted Departments in the object to be posted, I started facing this issue. So their input value is, RestrictedLocations = 300#,400#. RestrictedDepartments = 100#,200#. 

So when I try to post this object in Intaact via VendorCreate API call, I am facing the above mentioned issue. 

Can you help me understand what kind of issue is this and how this can be resolved.

**Comment by dylan-holt-sage** [comment]
@ThinkrAstha, based on the error, is a controlid being set for your request? If not, can you set the attribute and see what happens?
