### ISSUE TITLE
Updating Custom Objects

### ISSUE THREAD

**Issue by seanmunson** [Intacct/intacct-sdk-net#19]
Is it possible to update custom objects?

**Comment by jimmymcpeter** [comment]
Take a look at the examples in the guide.  We have an example that covers custom objects - https://developer.intacct.com/tools/sdk-net/custom-object-function/

**Comment by seanmunson** [comment]
Yes, creation or deletion, neither of which is the same as alteration.

**Comment by jimmymcpeter** [comment]
Ah yes - you'll still implement the IFunction interface/extend the AbstractFunction like the examples, but you need to use the update function in the API docs here - https://developer.intacct.com/api/platform-services/records/#update-record
