### ISSUE TITLE
AttachmentFile MUST reference a physical file path?

### ISSUE THREAD

**Issue by tchpowdog** [intacct/intacct-sdk-net#190]
Please add the ability to create an AttachmentFile with a byte array instead of having to provide a physical file path.  In the "cloud" world, this just isn't practical.  I have a service running in an Azure Function that needs to pull files out of cloud storage and push them into Intacct.  I can't create a temp local file in the Azure Function due to potential file sizes.

Is there a work around to this issue?  I have the byte array and the file is represented as a byte array in the end result XML anyway, but I can't get the byte array data into the "attachment" element.

The main problem is that AttachmentFile must contain a physical file path or the WriteXml method will not resolve.

**Comment by dylan-holt-sage** [comment]
@tchpowdog, we currently don't have plans to implement this, but please feel free to implement and raise a PR if you'd like to and we can review that. :)

**Comment by mike-at-cmap-software** [comment]
@dylan-holt-sage happy to have a look at implementing this. Do you want a new issue opened or to re-open this issue?

**Comment by dylan-holt-sage** [comment]
@mike-at-cmap-software, raise a PR when ready. No need for another issue or reopen :)
