### ISSUE TITLE
Getting error while creating order entry transaction

### ISSUE THREAD

**Issue by UmeshEnest** [intacct/intacct-sdk-net#191]

**Comment by UmeshEnest** [comment]
Getting Error
 71: Element 'sotransitems': Missing child element(s). Expected is ( sotransitem ).. Line: 1, column: 0.

**Comment by dylan-holt-sage** [comment]
@UmeshEnest , Can you provide more details as to what you're executing? What parameters are you sending? Is this still an issue?

**Comment by dylan-holt-sage** [comment]
Closing due to staleness..... If issue still persists, please reopen
