### ISSUE TITLE
project Task field is not present in AbstractExpenseReport class in.net SDK

### ISSUE THREAD

**Issue by kajalW** [intacct/intacct-sdk-net#192]
Hi,
we integrate with Intacct via .net SDK.
we export fully approved expense items into Intacct.
but the field is not present in AbstractExpenseReport class to map Project Task Dimension.
Could you please guide me to how can I map the Project Task field in the expense report in Sage Intacct?

**Comment by kajalW** [comment]
Hi,
Any updates on this issue?

**Comment by dylan-holt-sage** [comment]
Hey @kajalW, sorry for the late response..... I'll take a look at the missing field and keep you posted!
