### ISSUE TITLE
lookup on Timesheet give incorrect field

### ISSUE THREAD

**Issue by lbTustin** [intacct/intacct-sdk-net#193]
I do a lookup or inspect I get that there is a field named Lines# (with the number sign). However the Readby with fields as * <fields>*</fields> returns the XML with the field as Lines(no number sign)
<timesheet>
<RECORDNO>43</RECORDNO>
<DESCRIPTION>17846</DESCRIPTION>
<EMPLOYEEKEY>17</EMPLOYEEKEY>
<BEGINDATE>12/29/2018</BEGINDATE>
<ENDDATE>01/04/2019</ENDDATE>
<GLPOSTDATE>01/04/2019</GLPOSTDATE>
<EMPLOYEEID>jhoeppner</EMPLOYEEID>
<EMPLOYEENAME>Jim Hoeppner</EMPLOYEENAME>
<STATE>Approved</STATE>
<LINES>1</LINES>
</timesheet>

lookup results
<Field>
<ID>LINES#</ID>
<LABEL>Lines max index</LABEL>
<DESCRIPTION>No description specified</DESCRIPTION>
<REQUIRED>false</REQUIRED>
<READONLY>false</READONLY>
<DATATYPE>INTEGER</DATATYPE>
<ISCUSTOM>false</ISCUSTOM>
</Field>

**Comment by dylan-holt-sage** [comment]
Hey @lbTustin, we have also noticed this..... It is not an SDK issue and we will be reaching out to the respective team internally on this matter. Thanks for this :)

**Comment by lbTustin** [comment]
Please explain why you don't plan to address this.  How can one function advise of a field and then when you ask for the field it's not there.
