### ISSUE TITLE
How to input the billing address and shipping address while creating a new customer in Intacct via Intacct SDK

### ISSUE THREAD

**Issue by ThinkrAstha** [intacct/intacct-sdk-net#195]
While creating the customer via Intacct SDK , in the request body , there is option to input the primary address but how are we supposed to input the shipping and billing address of a customer.  

I do see an option of BillToContactName and ShipToContactName where we can input contact name  . How does this work . Do we have to create contacts separately for a company in Intacct or it takes the contact input from already existing customers/vendors/contacts of a company ? 

Please find the attached screenshots, which mentions about the fields I am mentioning about in the above query. 
<img width="754" alt="CustomerCreateRequest" src="https://user-images.githubusercontent.com/89450881/158844275-9f2510e8-d575-46af-9f74-bd216555e38e.png">
<img width="694" alt="CustomerCreateRequest1" src="https://user-images.githubusercontent.com/89450881/158844287-82f130ea-fef9-4dc0-8dec-7fb9105463f7.png">

Also, please find the link attached below for IntacctSDk API call to create a  customer : 

https://intacct.github.io/intacct-sdk-net/class_intacct_1_1_s_d_k_1_1_functions_1_1_accounts_receivable_1_1_abstract_customer.html

**Comment by ThinkrAstha** [comment]
By creating contacts separately, what I meant, was , to make a separate API call , to create a new contact altogether for a company in Intacct , please find the link below for creating a contact via Intacct SDK API  : 

https://intacct.github.io/intacct-sdk-net/class_intacct_1_1_s_d_k_1_1_functions_1_1_company_1_1_abstract_contact.html

**Comment by ThinkrAstha** [comment]
As I am in mid of my development, and there are deadlines to attend to , is it possible, if you could look into this quickly.
Appreciate your response. 

Thanks

**Comment by ThinkrAstha** [comment]
Can you please look into this issue for a quicker response . Thank you for your time.

**Comment by jhorn70** [comment]
I don't work for Sage.  The best way I have found to do this is to create the contacts in separate functions.  Give them a name like S_<CustomerID> and B_<CustomerID> and then use them in a function to create the customer record in an execute multiple.  You can turn on the transaction flag to ensure they all roll back together if there is a failure.

**Comment by dylan-holt-sage** [comment]
@jhorn70 is correct. So there are 2 things here......

First thing is that, for creating a new customer, the system will automatically use addresses provided in DISPLAYCONTACT for billing/shipping address assuming no others are provided. This will automatically create a CONTACT record as well.

Second thing is that if you want to have different billing/shipping information for a customer, there will need to be an already active contact record there and it would be referenced by the CONTACT name.

For reference: https://developer.intacct.com/api/accounts-receivable/customers/#create-customer

Hope this helps, closing this issue.
