### ISSUE TITLE
SDK  Customer DeliveryMethod not updating in Intacct

### ISSUE THREAD

**Issue by MikeSchlatter1234** [intacct/intacct-sdk-net#197]
I am unable to set the Customer's Delivery Options in Intacct.  

Possible Cause:

     The current API definition for Customer Create and Update lists "DELIVERY_OPTIONS".

     The SDK is updating "DELIVERYOPTIONS" which may be the problem.

            xml.WriteElement("DELIVERYOPTIONS", DeliveryMethod);

**Comment by dylan-holt-sage** [comment]
@MikeSchlatter1234 , that is a SDK bug, should be "DELIVERY_OPTIONS", we'll fix this

**Comment by dylan-holt-sage** [comment]
This will be in the next release, date TBD :)

**Comment by MikeSchlatter1234** [comment]
Thanks for working on this!

    On Friday, September 23, 2022 at 12:43:39 PM CDT, Dylan Holt ***@***.***> wrote:  
 
 


Closed #197 as completed.
