### ISSUE TITLE
ProjectId is not populated in PurchasingTransactionCreate and PurchasingTransactionUpdate

### ISSUE THREAD

**Issue by tructn** [intacct/intacct-sdk-net#198]
Hi,
We are currently integrate with Intacct and trying to populate ProjectID in Purchase Transaction but it seems not populated from the SDK ?

Is this an issue or we have another alternative solution ?

**Comment by dylan-holt-sage** [comment]
@tructn, I see that the field is there in the abstraction, but for some reason, it wasn't added to the Create/Update files for writing the XML....... We'll implement this :)

**Comment by dylan-holt-sage** [comment]
Changes for this will be in the next release. Closing this issue.
