### ISSUE TITLE
Tax details are either missing or don't belong to the tax solution

### ISSUE THREAD

**Issue by mickbaulch** [intacct/intacct-sdk-net#201]
Just trying to create a basic AP Bill in the system and get hit with the following error.

ResultException: Result status: failure for Control ID: f844fa93-16b8-46f9-875a-f6f33661b21f - BL01001973 Tax details are either missing or don't belong to the tax solution. [Support ID: X6d3pEB030%7EYoHkIP0z3J3--9mWDHwtDwAAABE] Ensure each line item has a tax detail that belongs to the applicable tax solution. - BL01001973 Currently, we can't create the transaction 'V100-001'. Check the transaction for errors or inconsistencies, then try again.

The code being used is

            Intacct.SDK.Functions.AccountsPayable.BillCreate NewInvoice = new Intacct.SDK.Functions.AccountsPayable.BillCreate()
            {
                VendorId = "V125",
                TransactionDate = DateTime.Now,
                BillNumber = "V125-001",
            };

            Intacct.SDK.Functions.AccountsPayable.BillLineCreate NewInvoiceLine = new Intacct.SDK.Functions.AccountsPayable.BillLineCreate()
            {
                TransactionAmount = 44,
                GlAccountNumber = "5002",
                VendorId = "V125",
            };

            NewInvoice.Lines.Add(NewInvoiceLine);

            Task<OnlineResponse> updateTask = client.Execute(NewInvoice);
            updateTask.Wait();

**Comment by MrSent** [comment]
You have to use the non legacy endpoints to create an AP Bill with Tax Entries in it.

**Comment by dylan-holt-sage** [comment]
@mickbaulch , did the advice above help solve your issue? If so, I'll close this.

**Comment by dylan-holt-sage** [comment]
closing this as stale, if it's still an issue, please re-open.
