### ISSUE TITLE
How do we use * to retrieve all fields?

### ISSUE THREAD

**Issue by jdohbeecanhealth** [intacct/intacct-sdk-net#204]
I am trying to modify bottom C# code to retrieve all fields.
I was informed (from other developer) that there are 3 ways to read most objects:

query (Query and List (new))
readByQuery (Query and List (legacy))
read (Get record specifying key)

readByQuery and read allow passing in a * to retrieve the complete object/all properties. query (new) requires you to explicitly define the fields you want returned.

        public static class List_APBILL
        {          
            public static string Run(ILogger logger)       
            {
                OnlineClient client = Bootstrap.Client(logger);

                SelectBuilder selectBuilder = new SelectBuilder();
                ISelect[] fields = selectBuilder.
                //Fields(new[] { "RECORDNO", "STATUS", "OPEN" }). // APBILLBATCH
                    Fields(new[]  { "*" } ). // APBILLBATCH
                    GetFields();

            int offset = 0;
            int pagesize = 100;
            string resultJsonString = "";

            //var query = new QueryFunction()
            var readByQuery = new QueryFunction()
            {
                FromObject = "APBILLBATCH",
                Offset = 0,                    
                PageSize = 20,
                SelectFields = fields
            };
           
            do
            {
                //query.Offset = offset;
                //query.PageSize = pagesize;
                readByQuery.Offset = offset;
                readByQuery.PageSize = pagesize;

                //Task<OnlineResponse> task = client.Execute(query);
                Task<OnlineResponse> task = client.Execute(readByQuery);
                OnlineResponse response = task.Result;
                Result result = response.Results[0];

                dynamic resultJson =
                           JsonConvert.DeserializeObject(JsonConvert.SerializeObject(result.Data));
                offset += pagesize;
                var x = Regex.Replace(resultJson.ToString(), @"[\[\]']+", "");
                resultJsonString += x + ",";

            } while (offset < 2001);  
            return "[" + resultJsonString + "]";
        }
    }
}

**Comment by dylan-holt-sage** [comment]
closing as you've found a solution :)
