### ISSUE TITLE
BL01001973 Could not create expenses record!

### ISSUE THREAD

**Issue by kajalW** [intacct/intacct-sdk-net#205]
Dear Concern,
I'm using intacct-sdk-net. I'm getting error while create an Expense Report. Please see the error below.

Errors:

BL03002101 Remove the extra line item in the request, then reclassify the bill.

[Support ID: 0EwG-EB030%7EYtrKeP022XG-nQqWy6tTfwAAACQ] -
BL01001973 Currently, we can't create the transaction . Check the transaction for errors or inconsistencies, then try again.

What is the reason I'm getting this error ? any suggestion please

**Comment by dylan-holt-sage** [comment]
@kajalW, What are you sending in? Not much to discern without more details.

**Comment by dylan-holt-sage** [comment]
Closing this due to not having enough information. Please reopen if this issue still persists.
