### ISSUE TITLE
Issue regarding the SDK does not return response after performing operation in Intacct

### ISSUE THREAD

**Issue by JaySoni19** [intacct/intacct-sdk-net#206]
Currently, I am using *intacct-sdk-net* version 3.0.0 in my Net 6.0 project. While using the SDK to do operations in Intacct, I sometimes run into the following problems

1. Whenever I perform any operation in Intacct, it is successful, but I don't receive a response from Inacct (intacct-sdk-net).
2. As an example, we could also call the intacct-sdk method, but without performing any operations in Intacct and the next operation is performed
Would there be any way to overcome this issue or any configuration settings that would prevent this from happening?

**Comment by dylan-holt-sage** [comment]
@JaySoni19, can you give a more concrete example?

**Comment by dylan-holt-sage** [comment]
if this issue is still occurring, please reopen
