### ISSUE TITLE
Create Payment for Specific Document

### ISSUE THREAD

**Issue by jmawebtech** [Intacct/intacct-sdk-net#21]
Hi,

I am trying to create a payment for a certain invoice, but my code fails. What fields are incorrect?

        private void CreatePayment(JMAPayment payment, SODOCUMENT doc)
        {
            GLACCOUNT account = accounts.Where(a => a.TITLE == settings.DefaultAccount).FirstOrDefault();

            ArPaymentCreate record = new ArPaymentCreate("unittest")
            {
                CustomerId = doc.CUSTVENDID,
                UndepositedFundsGlAccountNo = account.ACCOUNTNO,
                ReferenceNumber = payment.ReferenceNumber,
                TransactionPaymentAmount = payment.PaymentAmount,
                ReceivedDate = payment.PaymentDate,
                PaymentMethod = payment.CreditCardName,
                ApplyToTransactions = new List<ArPaymentItem>()
                 {
                      new ArPaymentItem()
                      {
                           AmountToApply = payment.PaymentAmount,
                           ApplyToRecordId = int.Parse(doc.DOCPARKEY)
                      }
                 }
            };

            records.Add(record);
        }

Here are the errors:

<errormessage><error><errorno>DL03000005</errorno><description></description><description2>No record exits for the recordkey 43</description2><correction></correction></error><error><errorno>DL03000005</errorno><description></description><description2>The key 43does not belong to an accounts receivable document.</description2><correction></correction></error><error><errorno>XL03000027</errorno><description></description><description2>The amount paid is greater than amount due for invoice with key 43</description2><correction></correction></error><error><errorno>BL03000129</errorno><description></description><description2>No such customer</description2><correction></correction></error></errormessage></result></operation></response>

**Comment by jimmymcpeter** [comment]
So this is where the line of Sage Intacct API support and SDK support gets blurred.  The API error is correct, there's nothing wrong with the SDK.  You are using the OE transaction record, which is incorrect.  You need to use the record of the AR Invoice instead.  Order Entry Invoices create AR Invoices

**Comment by jmawebtech** [comment]
Hi,

Thank you for your feedback. Can you tell me if I am associating the right ids fields from the customer and invoice objects?

**Comment by jimmymcpeter** [comment]
I don't know what the `doc` variable object structure is so it's kind of hard to help you with this.  Is this just the XML fields from a read SODOCUMENT response?  If it is, change this `ApplyToRecordId = int.Parse(doc.DOCPARKEY)` line to be `ApplyToRecordId = int.Parse(doc.PRRECORDKEY)`

**Comment by jmawebtech** [comment]
Thanks, that fixed my error and the payment was created successfully.

**Comment by jimmymcpeter** [comment]
The OE sales invoice auto creates the AR invoice and stores this key in the `PRRECORDKEY`.  You would use this to run a read to the `ARINVOICE` object, if you needed that info.  Payments in AR stick to Invoices in AR.
