### ISSUE TITLE
create_aradjustment missing supdocid

### ISSUE THREAD

**Issue by okmotsan** [intacct/intacct-sdk-net#217]
It appears that AR Adjustments support file attachments in the Intacct web portal, but not via the API.

The field "supdocid" is on the AR Invoice (create_invoice) in the API, but not on the AR Adjustment (create_aradjustment). This is inconsistent.

Why are file attachments on AR Adjustments not supported via the API if they are allowed on the web app?  My use case is to attach a PDF of the credit from our front end system to the AR Adjustment in Intacct.  This works for the invoices but not for credits.

![chrome_oxf7XrldaJ](https://user-images.githubusercontent.com/107003259/191115822-35a3e06a-84b8-440c-8b78-67b72b8c1d12.png)
![chrome_iTl3iog59E](https://user-images.githubusercontent.com/107003259/191115825-0c1f9b8d-12b4-4816-8cf2-862dce32df54.png)
![chrome_RIHAErFf4e](https://user-images.githubusercontent.com/107003259/191116019-4a9d378d-8e44-4026-9216-2c29d12ec049.png)

**Comment by okmotsan** [comment]
Further, I tried to modify the SDK class ArAdjustmentCreate to add in the missing supdocid but then Intacct returns this error:

Response control status failure - XL03000003 XML Parse schema error: Error 1871: Element 'supdocid': This element is not expected. Expected is one of ( description, externalid, basecurr, currency, nogl, taxsolutionid, aradjustmentitems ).. Line: 1, column: 0. [Support ID: QTZJpEB034%7EYyjbdP0K2dA--EgW8s3vegAAABg]

**Comment by dylan-holt-sage** [comment]
@okmotsan, for whatever reason, the team that works on AR features did not add support for supdocid for AR Adjustments for the API when they created them..... There's nothing we can do at this time for this on the SDK front, unfortunately :(

**Comment by okmotsan** [comment]
Thanks for the update. I'd like to request this feature (correction?) from the API team, if this github for the SDK isn't the right place then can you please let me know where or who I should contact to log my request?
