### ISSUE TITLE
Xml Parse fails when Intacct Passes slash character in tag names.

### ISSUE THREAD

**Issue by seanmunson** [Intacct/intacct-sdk-net#22]
Intact returned the following tag : 

<GLDIMBuild/Disassemble_Kits_Transaction_Detail></GLDIMBuild/Disassemble_Kits_Transaction_Detail>

Needless to say, the C# Xml Parser barfs when it tries to parse the return message: 

    {System.Xml.XmlException: '/' is an unexpected token. The expected token is '>'. Line 1, position 2277.   at System.Xml.XmlTextReaderImpl.Throw(Exception e)   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)   at System.Xml.XmlTextReaderImpl.ParseElement()   at System.Xml.XmlTextReaderImpl.ParseElementContent()   at System.Xml.XmlTextReaderImpl.Read()   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)   at System.Xml.Linq.XDocument.Load(Stream stream)   at Intacct.Sdk.Xml.AbstractResponse..ctor(Stream body) in C:\projects\Rpb\SF2Rpb\intacct-sdk-net-master\src\Xml\AbstractResponse.cs:line 37}

This error occurs in the AbstractResponse.cs file on the first line of the Constructor for the AbstractResponse Class 

    xml = XDocument.Load(body);

So does this mean that we need to build a better XML parser, or does Intacct need to reform its tag construction ?

**Comment by jimmymcpeter** [comment]
This is a known Intacct issue with user defined dimensions.  You need to talk to whoever the admin of this company is.  They need to go to the object definition and edit the lookup field `Document Entries [GLDIMBuildDisassemble_Kits_Transaction_Detail]` and remove the slash from the integration name.

Screenshot -- https://i.imgur.com/QD2OE4V.png

**Comment by jimmymcpeter** [comment]
@seanmunson do you have access to create a support case at https://community.intacct.com ?  I want this fixed in the application and a case is the best way to do get it moving.

**Comment by jimmymcpeter** [comment]
I see you have a case open now. I'm going to close this issue here on github.  Reference 00227890
