### ISSUE TITLE
Query Using Date Range

### ISSUE THREAD

**Issue by jmawebtech** [Intacct/intacct-sdk-net#25]
Hi,

I would like to query payments created from 2/1/2018 to 2/28/2018. Can I query using a date range?

        public List<ARPAYMENT> SearchPaymentsByDate(DateTime beginDate, DateTime endDate)
        {
            GreaterThanOrEqualToDateTime query = new GreaterThanOrEqualToDateTime()
            {
                Field = "WHENCREATED",
                Value = beginDate
            };

            LessThanOrEqualToDateTime query = new LessThanOrEqualToDateTime ()
            {
                Field = "WHENCREATED",
                Value = endDate
            };

            ReadByQuery readByQuery = new ReadByQuery()
            {
                ObjectName = "ARPayment",
                Fields = { "*" },
                Query = query
            };

            Task<OnlineResponse> task = Client().Execute(readByQuery);
            task.Wait();
            OnlineResponse response = task.Result;
        }

**Comment by jimmymcpeter** [comment]
Yeah, you can use the `AndCondition` class with your two queries as conditions in it.  Check out the test for it here - https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK.Tests/Functions/Common/Query/Logical/AndConditionTest.cs#L40
