### ISSUE TITLE
Retrieve XML Response returned by Intacct SDK.

### ISSUE THREAD

**Issue by wgawIQ** [intacct/intacct-sdk-net#254]
Our goal is to be able to retrieve the XML Response when making API calls via Intacct SDK.

I have found this [article](https://developer.intacct.com/tools/sdk-net/#logging) but am unable to figure out how to extract the XML Response using this.

I also did some digging on the code of Intacct SDK and found where the XML Response is contained in _AbstractResponse_, but I am unable to access it from _OnlineResponse_ due to the protected access modifier. I also didn't find the request in XML form anywhere.

Can someone assist with this?

**Comment by SergioBAM** [comment]
Have you looked at this: https://github.com/intacct/intacct-sdk-net-examples
Look at the CRUDCustomer or GettingStarted files for more info.

You're essentially: 
Task<OnlineResponse> response = await client.Execute(request);
From that response you have full access to all the properties.

**Comment by wgawIQ** [comment]
Hi @SergioBAM!

Thanks for the quick response. 

Yes, I have checked those files previously and we already have `var response = await client.Execute(request);` implemented. The problem is that I could not access OnlineResponse.Response since Response is protected within AbstractResponse where OnlineResponse is inherited from.

Thanks,
Chester

**Comment by SergioBAM** [comment]
Because it builds it from the XML returned. See Intacct.SDK.Xml.Response

Remove your line 54 and debug the Result result = response.Results[0];

What exactly are you trying to do?

**Comment by wgawIQ** [comment]
Hello, @SergioBAM.

What I am trying to achieve is to get the API response in XML format. Just like how we would receive the response in Postman.

Thanks,
Chester

**Comment by wgawIQ** [comment]
Hey @Ansh-S thanks for this. This is exactly what I need.
