### ISSUE TITLE
Create Journal Entries

### ISSUE THREAD

**Issue by jmawebtech** [Intacct/intacct-sdk-net#27]
Hi,

How do I assign a TR type?

In this example, there is a TR Type:

https://developer.intacct.com/api/general-ledger/journal-entries/#create-journal-entry

In your test, it appears TR Type is hidden:

https://developer.intacct.com/api/general-ledger/journal-entries/#create-journal-entry

How does Intacct know whether the line is a credit or debit?

**Comment by jimmymcpeter** [comment]
Positive amounts will be a debit, negative will be a credit. See this line in the source - https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/<https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/GeneralLedger/JournalEntryLineCreate.cs#L35>GeneralLedger<https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/GeneralLedger/JournalEntryLineCreate.cs#L35>/JournalEntryLineCreate.cs#<https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/GeneralLedger/JournalEntryLineCreate.cs#L35>L35<https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/GeneralLedger/JournalEntryLineCreate.cs#L35>



From: Joseph Anderson
Sent: Tuesday, March 6, 7:08 AM
Subject: [Intacct/intacct-sdk-net] Create Journal Entries (#27)
To: Intacct/intacct-sdk-net
Cc: Subscribed


Hi,
How do I assign a TR type?
In this example, there is a TR Type:
https://developer.intacct.com/api/general-ledger/journal-entries/#create-journal-entry
In your test, it appears TR Type is hidden:
https://developer.intacct.com/api/general-ledger/journal-entries/#create-journal-entry
How does Intacct know whether the line is a credit or debit?

**Comment by jmawebtech** [comment]
Hi,

When I create an entry, I get this error:

The user does not have an employee associated

Is there an employee ID field I can use?

**Comment by jimmymcpeter** [comment]
The user you are using to create the JE is not linked to a corresponding employee record.  You should contact the company admin or customer support for help with this.
