### ISSUE TITLE
ShipVia

### ISSUE THREAD

**Issue by jmawebtech** [Intacct/intacct-sdk-net#29]
Hi,

On the Sage Intacct order entry area, there is a field called ship via. Before I populate the field, I want to ensure my record exists in the list. Will Sage Intacct create the record automatically, if it is missing? I am trying to query the ShipVia object, but my code says no object exists:

            ReadByQuery readByQuery = new ReadByQuery()
            {
                ObjectName = "SHIPVIA",
                Fields = { "*" },
            };

What is the object name?

**Comment by jimmymcpeter** [comment]
Unless it's listed [here](https://developer.intacct.com/api/), it's likely not exposed to the API.
