### ISSUE TITLE
Response Error Handling always throwing errors

### ISSUE THREAD

**Issue by EricDGriffith** [Intacct/intacct-sdk-net#32]
Line 54 of Intacct.SDK.OnlineClient calls the method EnsureStatusSuccess.  This will throw a hard exception with the primary request is successful, but the response contains errors in the errormessage response body.  Once this happens, you cannot use the result object or figure out what the actual errors are.  You can only find this out in the log file by examining the text file where the response body is written.  It makes no sense to throw this exception since the there is a success property to test against and I want to use the error messages for internal error handling.  This happens with any response that fails business logic validation and makes the whole result object useless.  How do others deal with the error handling?

**Comment by jimmymcpeter** [comment]
The `ResultException` extends `ResponseException` -- this has the `Errors` property which is a `List<string>` built on [this line](https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Xml/Response/Result.cs#L78) - we use this a little in the examples [here](https://github.com/Intacct/intacct-sdk-net-examples/blob/master/Intacct.Examples/Program.cs#L73) to add it to the logger

**Comment by EricDGriffith** [comment]
Your response was just enough for me to figure out the issue.  It was NOT clear at all that any response the "IsFaulted" throws an exception.  Based on the class design and API documentation, it seemed like testing the value of the response would allow me to manage the process without using exceptions.  While it is a design choice, it was extremely confusion.  And ZERO documentation.

**Comment by jimmymcpeter** [comment]
If you don't mind submitting some feedback on the docs to our tech writers -- At the bottom of [this page](https://developer.intacct.com/tools/sdk-net/#error-handling) there is a provide feedback link.  Ask them to better clarify the error handling for status failures and how to handle/process those.
