### ISSUE TITLE
Bill Update/Purchase Order Update

### ISSUE THREAD

**Issue by jcford01** [Intacct/intacct-sdk-net#33]
Are there planned expansions for these functions for these object types? Update exists for other object types such as vendor, customer, etc. If not, can you suggest a method by which I write a custom call?

For more specifics, my company consistently puts specific bills on hold and takes them off of hold. While I have a workaround currently in place, it doesn't perform well when the transactions in question are in locked periods.

Thanks!

**Comment by jimmymcpeter** [comment]
It can be added to the enhancement list for future. I don't see it as anything crazy since we already have the abstract objects.  If you needed it this very minute, you can implement the `IFrunction` yourself like fpmess did [for this issue](https://github.com/Intacct/intacct-sdk-net/issues/30).
