### ISSUE TITLE
Update NLog package to use 4.5.0

### ISSUE THREAD

**Issue by jimmymcpeter** [Intacct/intacct-sdk-net#34]
NLog is finally out of RC, update package to use this - https://github.com/NLog/NLog/releases/tag/v4.5

**Comment by rposener** [comment]
Any reason not to use Microsoft.Extensions.Logging.ILogger abstraction instead of NLog specifically?

**Comment by jimmymcpeter** [comment]
At the time I lost some hair that day trying to figure out NLog's package that supported Microsoft.Extensions.Logging.ILogger abstraction properly with the versions the SDK supported.  It looks like they've pushed some updates to it so I'll take a look.

**Comment by jimmymcpeter** [comment]
Using issue #47 to track using Microsoft.Extensions.Logging.Abstractions instead of NLog
