### ISSUE TITLE
how to get client list using  <get_myclients/>   API function

### ISSUE THREAD

**Issue by Sunny0989** [Intacct/intacct-sdk-net#57]
We are getting My Client list using **<get_myclients/>** as per your given step using postman.

just like for genrate sessionId  using class "ApiSessionCreate". but, not find any class/function for "get_myclients" to get client list using .Net SDK. Please let us know how to get the details.

**Comment by jimmymcpeter** [comment]
You can implement the IFunction interface for that function just like this comment - https://github.com/Intacct/intacct-sdk-net/issues/30#issuecomment-375352053

**Comment by Sunny0989** [comment]
thanks it will work
