### ISSUE TITLE
SDKConfig not defaulted properly

### ISSUE THREAD

**Issue by rposener** [Intacct/intacct-sdk-net#6]
We are using the SDK, and Create a Client with a SdkConfig that includes a longer timeout than the 5 minutes (our batch is taking 9 minutes to process).  Later when Execute methods are called, they don't default off the SdkConfig passed into the IntacctClient constructor.  

This is very confusing and since the execute has the SdkConfig parameter as optional, one would assume that the IntacctClient would default from the constructor's copy.  I would recommend you guys default the SdkConfig differently in the Execute and ExecuteAsync methods of the IntacctClient.  At minimum support the defaulted timeout value from the value passed into the constructor.

**Comment by rposener** [comment]
Submitted fix on #7 pull request.

**Comment by jimmymcpeter** [comment]
@rposener take a look at the v2.0 branch.

**Comment by rposener** [comment]
@jimmymcpeter thanks - I see the MaxTimeout on the RequestConfig - a better option, but what is the argument to not have a default set on the client?  At the point I'm injecting a Client into my code via a DI container, I would expect the configuration to be done, and I can just use the Client.  Is there an argument against not setting a default on the client to be used if the optional RequestConfig is not provided at the time of the call?

**Comment by jimmymcpeter** [comment]
We use the HttpClient, so you might be able to set InfiniteTimeSpan. I'm not going to be able to try this for a few days -- https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.timeout(v=vs.110).aspx

Just note that when you go over 300 seconds you start flirting with danger.  The CDN will cut connections after 10 or 15 mins I think. You should use unique control IDs to help with idempotence. Also might be worth looking at async requests with a policy ID.
________________________________
