### ISSUE TITLE
How to set Address information on OE Transaction?

### ISSUE THREAD

**Issue by michaelpaulus** [Intacct/intacct-sdk-net#63]
When creating an Order Entry Transaction, how do we set the billing / shipping address information (like address1, 2, state, city, ...)?  I know I can set the contact name, but I may have different address information than the contact through our eCommerce system for that single order.  We don't want to create individual contacts for every deviation they could enter into the store, we just want to capture that on the invoice itself.  When I get the sales invoice back, I can get at all the individual pieces of the contact information, like BILLTO.MAILADDRESS.ADDRESS1, so I know you have data elements for it internal to the system.

Thanks.

**Comment by jimmymcpeter** [comment]
This is unfortunately how the system works.  You have to reference a separate contact record from the OE transaction.  If you login to the UI, its done the same way on the create sales invoice screen - user has to select an existing or create a new contact record.

The SDK code in OrderEntryTransactionCreate.cs could be changed to create a billto/shipto contact inside the create_sotransaction, but you still need the contactname to be unique.

```xml
  <xs:element name="billto">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="contact"/>
        <xs:element ref="contactname"/> <!-- the SDK uses this element for an existing contact, instead of creating a new one -->
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="contact">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contactname"/>
        <xs:element ref="printas"/>
        <xs:element ref="taxable" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="companyname" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="taxgroup" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="prefix" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="firstname" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="lastname" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="initial" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="phone1" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="phone2" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="cellphone" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="pager" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="fax" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="email1" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="email2" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="url1" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="url2" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="status" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="mailaddress" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="taxid" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
```

**Comment by michaelpaulus** [comment]
Thanks, I can just create unique contacts outside of this then and pass the contact name in.
