### ISSUE TITLE
Howto create AR Advance through SDK

### ISSUE THREAD

**Issue by michaelpaulus** [Intacct/intacct-sdk-net#64]
I'm attempting to create an advance through the SDK, I left the ApplyToTransactions empty and specified an UndepositedFundsGlAccountNo.  I have the correct advance account setup in AR, but I see no place to specify the location for the advance and get this error message:

Result status: failure for Control ID: 91ab330f-58eb-4f28-a5dd-a7e7ad42cec6: BL03001994 Use of empty Location is invalid. A valid Multi-Entity Location must be specified, BL03001994 Use of empty Location is invalid. A valid Multi-Entity Location must be specified.

            var payment = new ArPaymentCreate()
            {
                CustomerId = customerId,
                TransactionPaymentAmount = amount,
                PaymentMethod = paymentMethod,
                ReceivedDate = paymentDate,
                UndepositedFundsGlAccountNo = "1030",
            };

            _intacctClientDal.CreateArPayment(payment).RunSync();

**Comment by jimmymcpeter** [comment]
I think you need to set an `OverpaymentLocationId` - https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/AccountsReceivable/ArPaymentCreate.cs#L48-L49

**Comment by michaelpaulus** [comment]
That worked, thanks!
