### ISSUE TITLE
Bill attachment

### ISSUE THREAD

**Issue by ifracea** [Intacct/intacct-sdk-net#68]
I am trying to create an attachment file for a bill previously created using sdk, but I receive an error.

```c#
var attachfile = new AttachmentFile()
{
	FileName = "test",
	Extension = "txt",
	FilePath = "D:\\test.txt"
};

var files = new List<AttachmentFile>();
files.Add(attachfile);

var attach = new AttachmentsCreate()
{
	ControlId = billControlId,
	Files = files,
	
};

Task<OnlineResponse> attachTask = client.Execute(attach);
attachTask.Wait();
```

I receive this error:

>XL03000003 XML Parse schema error: Error 1871: Element 'attachment': Missing child element(s). Expected is ( attachmentdata ).. Line: 1, column: 0.

There isn't any data or attarchment data for AttachmentFile.
I am missing something?

Thank you

**Comment by jimmymcpeter** [comment]
It looks like the code doesn't think your file exists.  See [line 72 here](https://github.com/Intacct/intacct-sdk-net/blob/master/Intacct.SDK/Functions/Company/AttachmentFile.cs#L72).  Would you prefer the code should throw an exception instead?

**Comment by ifracea** [comment]
Thank you,
There will be any option to send directly attachment data base64? or will stay just with path. my stream is in memory. Thank you.

**Comment by jimmymcpeter** [comment]
You can implement the IAttachment interface in your own class...  Something like this:

```c#
using System;
using System.IO;
using Intacct.SDK.Functions.Company;
using Intacct.SDK.Xml;

namespace Intacct.Examples
{
    public class AttachmentFileStream : IAttachment
    {
        public string Extension;
        public string FileName;
        public MemoryStream MemoryStream;

        public AttachmentFileStream()
        {
        }
        
        public void WriteXml(ref IaXmlWriter xml)
        {
            xml.WriteStartElement("attachment");

            // The file name without a period or extension - Ex: Invoice21244
            // Needs to be unique from other files in attachment record
            xml.WriteElement("attachmentname", FileName, true);

            // The file extension without a period - Ex: pdf
            xml.WriteElement("attachmenttype", Extension, true);

            xml.WriteElement("attachmentdata", Convert.ToBase64String(MemoryStream.ToArray()), true);

            xml.WriteEndElement(); //attachment
            
        }
    }
}
```
