### ISSUE TITLE
readByQuery Child Object

### ISSUE THREAD

**Issue by h-morales** [Intacct/intacct-sdk-net#69]
Is there anyway we can use the child objects field for readbyquery such as below?

```
 <readByQuery>
          <object>APPAYMENT</object>
          <query>ITEMS.RECORDID = 'TEST 101'</query>
          <fields>*</fields>
          <pagesize>10</pagesize>
          <returnFormat>xml</returnFormat>
        </readByQuery>
```

**Comment by jimmymcpeter** [comment]
Unfortunately, joins are not supported by readByQuery

**Comment by h-morales** [comment]
Is there a way to query APPayment using invoice number?

**Comment by jimmymcpeter** [comment]
I would post your question to the Developers group on the Sage Intacct Community.  It's the top link on this page -- https://developer.intacct.com/support/

A few hundred people watch that group compared to the SDK GitHub issues here.  The issues here are meant more for code-level assistance or bugs with the SDK itself.
