### ISSUE TITLE
Rev Rec Schedule for OE Line

### ISSUE THREAD

**Issue by michaelpaulus** [Intacct/intacct-sdk-net#71]
How do I query and get a specific rev rec schedule that is generated because of an order entry line item?

**Comment by jimmymcpeter** [comment]
I believe one of the [examples here](https://developer.intacct.com/api/general-ledger/revenue-recognition-schedules/#list-revenue-recognition-schedule-entries) shows the xml for this

```xml
<readByQuery>
    <object>REVRECSCHEDULEENTRY</object>
    <fields>*</fields>
    <query>DOCENTRYKEY = 21</query> <!--From the originating SODOCUMENT-->
    <pagesize>100</pagesize>
</readByQuery>
```
