### ISSUE TITLE
How do we send over line item sales tax information on Order Entry creation

### ISSUE THREAD

**Issue by michaelpaulus** [Intacct/intacct-sdk-net#73]
I would like to create an order entry transaction, we have line level sales tax information from our ecommerce store, we need to send this over when creating the order entry transaction through the api, can you point me in the right direction as it is not obvious on how to do this using the OrderEntryTransactionLineCreate object.

**Comment by jimmymcpeter** [comment]
Do you have line level taxes actually setup and configured for use when you go into the UI OE transaction screen?  I don't think we added them to the SDK because they were not widely used at the time.

**Comment by jimmymcpeter** [comment]
I think it might just be a matter of adding a new property to the `OrderEntryTransactionLineCreate` to output the `linelevelsimpletaxtype` XML element.  I don't have a company lying around with this turned on but the docs describe it as, 
> Simple tax rate to apply at the line level. Available only if Enable subtotals and Enable line level Simple Tax are enabled for the transaction definition.

**Comment by michaelpaulus** [comment]
I guess what I'm looking for is, I see how I can add subtotals to the header, but how do I specify which line the subtotal applies to?  

I'm not sure I have Enable line level Simple Tax turned on, but I don't see an option for this in the transaction definition.  When I try and pass linelevelsimpletaxtype over it fails.

**Comment by michaelpaulus** [comment]
I figured out how to add  linelevelsimpletaxtype but I get an error when sending it over through the api, and this isn't exactly what I'm looking for.  What I need the ability to do is say line 1 is taxed 6% and line 2 is taxed 8% and line 3 is taxed 0%.  Can I pass over subtotals per line?  

The error I get when passing over linelevelsimpletaxtype is:

XL03000003 XML Parse schema error: Error 1871: Element 'linelevelsimpletaxtype': This element is not expected. Expected is one of ( departmentid, memo, itemdetails, customfields, revrectemplate, revrecstartdate, revrecenddate, renewalmacro, projectid, customerid ).. Line: 1, column: 0.
