### ISSUE TITLE
Unable to set LocationId on getAPISession when when using SessionProvider.Factory

### ISSUE THREAD

**Issue by chz160** [Intacct/intacct-sdk-net#87]
The SessionProvider.Factory method does not provide any means of setting the locationId on the getAPISession node when authenticating and retrieving the initial sessionid.

My workaround was to create my own  CustomApiSessionCreate class and CustomSessionProvider class to uses it. The CustomApiSessionCreate class simply changes 
```xml
<getAPISession />
```
to
```xml
<getAPISession>
   <locationid>some_location_id</location>
</getAPISession>
```

as denoted on this blog post:
https://developer.intacct.com/blog/2018/10/2018-Release-4.html

```c#
public class CustomApiSessionCreate : AbstractFunction
{
    public CustomApiSessionCreate(string controlId = "")
        : base(controlId)
    { }

    public override void WriteXml(ref IaXmlWriter xml)
    {
        xml.WriteStartElement("function");
        xml.WriteAttributeString("controlid", this.ControlId);
        xml.WriteStartElement("getAPISession");
        xml.WriteElementString("locationid", "some_location_id"); //obviously hard coding a value here is not ideal.
        xml.WriteEndElement();
        xml.WriteEndElement();
    }
}
```

**Comment by jimmymcpeter** [comment]
Thanks @chz160 - a few folks have been on vacation since it was released.  We'll get it added soon to the SDK's ApiSessionCreate class.  In the mean time, I mentioned in your other issue #88 you can pipe on the entity ID to the company ID, if you're using login-based credentials.
