### ISSUE TITLE
How to get fulfillment status on SODOCUMENTENTRY

### ISSUE THREAD

**Issue by michaelpaulus** [Intacct/intacct-sdk-net#90]
I've tried all I can and looked at the object definition, but cannot figure out how to get the fulfillment status of an OE transaction line item through the api readByQuery.  Can you help please?

**Comment by jimmymcpeter** [comment]
Sorry I was out on vacation and managed to completely miss your issue.  I'm rusty on my fulfillment, but if you are viewing a transaction in the UI the Fulfillment Status field is displayed as a hyperlink.  This opens a popup to a record in the VSOEKITALLOCATION object, which is not exposed to the API.
