### ISSUE TITLE
Couldn't Write off an Invoice Using SDK

### ISSUE THREAD

**Issue by MaxPoon** [Intacct/intacct-sdk-net#91]
I want to know how I can save the payment when I  write off an invoice using C# sdk.
For example, there's an original invoice for $100. I created another invoice for $-100 to write off the original one. To manually save the payment, I go to "Account Receivable -> Receive a Payment", select both the original and the write-off invoices, set the payment amount to 0, and clicked "Save". This can be done successfully on the website. I tried to create the payment using C# sdk.

In my C# code, I create the ArPaymentCreate object with two ArPaymentItem. I apply one of the items to the original invoice ($100) and the other one to the write-off invoice ($-100) and set the payment amount to $0. But I got the error message "XL03000027 The amount paid is greater than amount due for invoice". I tried to replace the invoice with the Ar Adjustment but still got the same error. I opened a ticket on Intacct Support site, but I was asked to open the issue here for code-related issues. Could you let me know how I can save the payment with Intacct C# sdk? Thanks!

**Comment by jimmymcpeter** [comment]
Whoever told you to open an issue here was wrong -- this is an issue with the API not the SDK.  What's the case number with Intacct support?

**Comment by MaxPoon** [comment]
I agree with you @jimmymcpeter. The case number is 00260866.

**Comment by jimmymcpeter** [comment]
Here is my advice:  Open a new case so they don't get confused.  In the case provide a sample API function in XML you are sending (which I think you originally did).  The SDK can log this for you, or you can just do use Postman to hit the API directly.  Make sure you ask them what is the proper API function **and** an example in XML that you need to submit to the API to write off the invoice.  If they can give you this, then you and I can quickly figure out how to do it with the SDK.

The second you ask them how to do this in the SDK, they send you here.  I don't have access to your Intacct environment to be a whole lot of help.  I'd have to manually recreate this in my own demo company and hope it matches yours.

**Comment by MaxPoon** [comment]
I've opened a new case, case number: 00264608
