### ISSUE TITLE
Passing User Defined dimensional data through .NET SDK

### ISSUE THREAD

**Issue by taylorcook-por** [Intacct/intacct-sdk-net#93]
How do you pass dimensional data? My User Defined dimension is called "Seasonal". I'm trying to pass data to Intacct using the PurchasingTransactionLineCreate object and JournalEntryLineCreate object. Looking to add PurchasingTransactionLineCreate .Seasonal = "Spring", similar to how you would add PurchasingTransactionLineCreate.ClassID = "C001", etc. I have tried using the CustomFields property with a dictionary like <"Seasonal", "Spring">, but can't get it to work, I must be approaching it wrong.

**Comment by jimmymcpeter** [comment]
You'll want to use the `Integration Name` of the Lookup field on the object.  In my company, I have a `Line of Business` UDD object setup.  The system auto creates these lookup fields on the various transaction line objects with a `GLDIM` prefix, but keep in mind these can be changed by an admin.  Here is a screenshot of mine -- 

![image](https://user-images.githubusercontent.com/11491046/52061427-42c54200-253c-11e9-809e-7a85a510e508.png)

As for setting the value on the purchasing transaction line -- UDD's a bit different from standard dimensions, so the value you need to pass into this is the `id` of the UDD record, not the `name`.  My UDD record is named `Channel`, but the id is set by the system on creation.  In this example it's `10003`.

Here is an example using the SDK I just tried in my company to create a PO--

```c#
PurchasingTransactionCreate record = new PurchasingTransactionCreate()
{
    TransactionDefinition = "Purchase Order",
    TransactionDate = new DateTime(2019, 01, 31),
    VendorId = "20000",
    DueDate = new DateTime(2019, 02, 15),
    BaseCurrency = "USD",
    TransactionCurrency = "USD",
};

PurchasingTransactionLineCreate line1 = new PurchasingTransactionLineCreate()
{
    ItemId = "100",
    Quantity = 10,
    Unit = "Each",
    Price = 1.99M,
    LocationId = "100",
    DepartmentId = "D100",
    VendorId = "20000",
    CustomFields = new Dictionary<string, dynamic>
    {
        { "GLDIMLine_of_Business", "10003" },
    },
};
record.Lines.Add(line1);
```

**Comment by jimmymcpeter** [comment]
If you didn't like the CustomFields element and wanted your own `Seasonal` property, you could extend the PurchasingTransactionLineCreate or AbstractPurchasingTransactionLine.  These implement the IXmlObject interface.

**Comment by taylorcook-por** [comment]
Thanks. I had everything the same except I didn't append "GLDIM" to the front of my UD name when trying to pass it over. That seemed to resolve it.

**Comment by taylorcook-por** [comment]
Something to note... Integration Name on the UD object was just shown as "Seasonal". Integration Name on the Purchasing Document Detail Object had the "GLDIMSeasonal"
![3](https://user-images.githubusercontent.com/47216836/52062410-160e2c00-2536-11e9-899a-c85e77a11084.PNG)
![1](https://user-images.githubusercontent.com/47216836/52062411-160e2c00-2536-11e9-8c0c-a162aefeacca.PNG)
![2](https://user-images.githubusercontent.com/47216836/52062412-16a6c280-2536-11e9-8016-cc98e7f37ac1.PNG)

**Comment by jimmymcpeter** [comment]
>Thanks. I had everything the same except I didn't append "GLDIM" to the front of my UD name when trying to pass it over. That seemed to resolve it.

Just be careful assuming the UDD lookups will always have a `GLDIM` prefix.  I've seen some integrations run for months creating transactions, to later find out by an upset user that some fields haven't been getting set.  The API will not throw an error if the custom field you're trying pass in doesn't actually exist.

>Something to note... Integration Name on the UD object was just shown as "Seasonal". Integration Name on the Purchasing Document Detail Object had the "GLDIMSeasonal"

Yes objects have an integration name and the fields on objects have their own integration name. They are not the same.

**Comment by taylorcook-por** [comment]
Where does that prefix come from?

**Comment by jimmymcpeter** [comment]
It's set by the Intacct application code when you enable a custom object as a GL Dimension (UDD).  I mentioned above full admins can change these.  Looking at your screenshot you're a full admin, so you have that little `Edit` action on the left hand side.  However it's likely not hurting anything being auto-named `GLDIMSeasonal` so I would not change it -- your company may have other integrations/CSV imports/platform apps already using it and I doubt you want to break those.

**Comment by taylorcook-por** [comment]
Thanks. Very helpful. I appreciate your responses.
