### ISSUE TITLE
Why is IXmlWriter.WriteXml passed by ref?

### ISSUE THREAD

**Issue by InPermutation** [Intacct/intacct-sdk-net#95]
The method signature for `IXmlObject.WriteXml` is

    void WriteXml(ref IaXmlWriter xml);

Why? Writing XML should not have a side effect of changing the storage location of the writer passed to the method.

This `ref` in the signature means I can't use a `using` block in C#, because it has a compilation error:

    CS1657 - Cannot use 'writer' as a ref or out value because it is a 'using variable'

**Comment by intacctcoleenho** [comment]
Since you are trying to use "using" are you running >= .NET Core 3.0?

**Comment by intacctcoleenho** [comment]
Why are you stating the storage location of the writer (IaXmlWriter) is changing when writing XML?

**Comment by InPermutation** [comment]
Hi @intacctcoleenho, that’s what the `ref` keyword means in C#.

**Comment by intacctcoleenho** [comment]
Yes, it is working as designed then. 
`IaXmlWriter xml` is expected be modified by the `WriteXml` method and any subsequent methods `WriteXml` makes.  That is why it is `ref IaXmlWriter xml`.
