### ISSUE TITLE
Delete  AP Adjustments and Bill transaction lines

### ISSUE THREAD

**Issue by sfiodorov** [Intacct/intacct-sdk-net#97]
Hi.
Assuming i have AppAjUstment or Bill on intacct with lines 1,2,3 and i want to update it to have only one line Id 1. 
How to do that ?
updatelineitem is used to update existing lines.
lineitem is used to add new lines
But how to delete ?

**Comment by jimmymcpeter** [comment]
The API doesn't support deleting specific lines.  From what I know, you will likely have to set the line amount to zero.

**Comment by sfiodorov** [comment]
Thanks @jimmymcpeter
