### ISSUE TITLE
How to get payment details from Ap Payment

### ISSUE THREAD

**Issue by tqrecords** [Intacct/intacct-sdk-net#98]
I am trying to link an Ap Payment to and Ap Bill. In the reference documentation it appears as though they are linked through a child object called APPYMTDETAILS on the RECORDKEY property:

`
<APPYMT>
        <FINANCIALENTITY>CHK-BA1145</FINANCIALENTITY>
        <PAYMENTMETHOD>EFT</PAYMENTMETHOD>
        <VENDORID>V0001</VENDORID>
        <DOCNUMBER>12345</DOCNUMBER>
        <PAYMENTDATE>08/07/2017</PAYMENTDATE>
        <APPYMTDETAILS>
            <APPYMTDETAIL>
                <RECORDKEY>90</RECORDKEY>
                <ENTRYKEY>375</ENTRYKEY>
                <TRX_PAYMENTAMOUNT>50.00</TRX_PAYMENTAMOUNT>
            </APPYMTDETAIL>
        </APPYMTDETAILS>
    </APPYMT>
`

However, when using readByQuery this child node is not present. Is there a way to get this information through the SDK?

**Comment by jimmymcpeter** [comment]
readByQuery is a flat list view of the object and does not support "to-many" joins.  Try using `read` on the individual `APPYMT` record.  Alternatively you could use readByQuery on the `APPYMTDETAIL` with a query filter of PAYMENTKEY = the APPYMT's RECORDNO.

**Comment by tqrecords** [comment]
Thank you. The `read` not support `Fields` and `Query` parameters, so I ended up using `readByQuery` on the `APPYMTDETAIL` object using `RECORDKEY` against the original invoice/bill id.
